version: '3'

services:
  dbdstats:
    container_name: DBDStats
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: any
    environment:
      SENTRY_DSN: SENTRY_DSN_FOR_ERROR_REPORTING
      steamAPIkey: STEAM_APIKEY
      support_server: ID_OF_SUPPORTSERVER
      TOKEN: BOT_TOKEN
      OWNER_ID: DISCORD_ID_OF_OWNER
      twitch_client_id: twitch_client_id
      twitch_client_secret: twitch_client_secret
      libretransURL: URL_for_libretranslate
      libretransAPIkey: APIKey_for_libretranslate
    image: serpensin/dbdstats
    volumes:
      - dbdstats_log:/app/DBDStats
      - /PATH/TO/googleauth.json:/app/googleauth.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
    dbdstats_log:
