version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: MongoDB
    hostname: mongo
    restart: always
    volumes:
      - dbdata:/data/db
    networks:
      - dbd_net

  dbdstats:
    container_name: DBDStats
    ports:
      - "5000:5000"
    restart: always
    environment:
      SENTRY_DSN: SENTRY_DSN_FOR_ERROR_REPORTING
      steamAPIkey: STEAM_APIKEY
      support_server: ID_OF_SUPPORTSERVER
      TOKEN: BOT_TOKEN
      OWNER_ID: DISCORD_ID_OF_OWNER
      twitch_client_id: twitch_client_id
      twitch_client_secret: twitch_client_secret
      libretransURL: URL_for_libretranslate
      libretransAPIkey: APIKey_for_libretranslate
      MongoDB_host: mongo                                   #####################################
      MongoDB_port: 27017                                   #           Don't change!!!         #
      MongoDB_database: DBDStats                            #                                   #
      GOOGLE_APPLICATION_CREDENTIALS: /app/googleauth.json  #####################################
    image: serpensin/dbdstats
    volumes:
      - dbdstats:/app/DBDStats
      - /path/to/googleauth.json:/app/googleauth.json:ro
    depends_on:
      - mongo
    networks:
      - dbd_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dbd_net:

volumes:
  dbdata:
  dbdstats:
