services:
  dbdstats:
    container_name: DBDStats
    deploy:
      restart_policy:
        condition: any
    environment:
      steamAPIkey: STEAM_APIKEY
      support_server: ID_OF_SUPPORTSERVER
      TOKEN: BOT_TOKEN
      OWNER_ID: DISCORD_ID_OF_OWNER
      twitch_client_id: twitch_client_id
      twitch_client_secret: twitch_client_secret
      libretransAPIkey: APIkey_for_my_instance_of_libretrans
      MongoDB_host: IP_OR_DOMAIN_OF_MONGODB
      MongoDB_port: PORT_OF_MONGODB
      MongoDB_user: USER_OF_MONGODB
      MongoDB_password: PASSWORD_OF_MONGODB
      MongoDB_database: DATABASE_OF_MONGODB
      MongoDB_collection: COLLECTION_OF_MONGODB
    image: serpensin/dbdstats
    volumes:
    - dbdstats_log:/app/DBDStats/Logs
version: '3'
volumes:
    dbdstats_log: {}
